'use client';

import { styled } from '@mui/material/styles';
import { BASE_PATH } from '@/lib/base-path';

export const AboutHeroStyled = styled('div')(({ theme }) => ({
  background: theme.palette.grey[50],
  paddingTop: 'calc(var(--navbar-height, 0px) + 79px)',
  paddingBottom: '50px',
  paddingLeft: '50px',
  paddingRight: '50px',
  display: 'flex',
  flexDirection: 'column',
  gap: '24px',
  backgroundImage: `url("${BASE_PATH}/Sphere2026.png")`,
  backgroundPosition: 'bottom right',
  backgroundRepeat: 'no-repeat',
  backgroundSize: '560px auto',
  [theme.breakpoints.down('sm')]: {
    paddingTop: 'calc(var(--navbar-height, 0px) + 64px)',
    paddingBottom: '50px',
    paddingLeft: '0px',
    paddingRight: '0px',
    alignItems: 'center',
    textAlign: 'center',
    backgroundImage: `url("${BASE_PATH}/Sphere2026-half.png")`,
    backgroundSize: '50%',
  },
  '.header': { display: 'flex', flexDirection: 'column', gap: '0.5em', [theme.breakpoints.down('sm')]: { flexDirection: 'row' } },
  '.text-container': { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '24px' },
  '.text-info': { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '50px' },
  '.location-container': {
    display: 'flex',
    height: '110px',
    flexDirection: 'column',
    alignSelf: 'flex-end',
    borderRadius: '8px',
    [theme.breakpoints.down('sm')]: { paddingRight: '0px', alignSelf: 'center' },
  },
}));

export const AboutEmotionalVideoStyled = styled('div')(({ theme }) => ({
  background: `url('${BASE_PATH}/PatternHexagons.png') center center / 100% no-repeat,\n      linear-gradient(123deg, #003140 19.13%, #001015 105.03%)`,
  paddingBottom: '80px',
  display: 'flex',
  flexDirection: 'column',
  gap: '64px',
  alignItems: 'center',
  color: '#FFFFFF',
  [theme.breakpoints.down('md')]: { paddingBottom: '64px', gap: '32px' },
  '.gallery-description': {
    padding: '100px 10px 0px 10px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    width: '40vw',
    gap: '30px',
    [theme.breakpoints.down('sm')]: { padding: '100px 10px 50px 10px', width: '90%' },
  },
  '.video-container': { width: '90%', [theme.breakpoints.down('md')]: { width: '95%' } },
  '.watch-recap-button-container': { textAlign: 'center' },
}));

export const VenueSectionStyled = styled('div')(({ theme }) => ({
  display: 'flex',
  justifyContent: 'center',
  backgroundColor: theme.palette.grey[50],
  '.venue-container': {
    display: 'flex',
    width: '1176px',
    padding: '80px 0px 96px 0px',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '80px',
    [theme.breakpoints.down('md')]: { width: '100%', padding: '64px 16px 64px 16px', gap: '32px' },
  },
  '.text-container': { display: 'flex', gap: '24px', [theme.breakpoints.down('md')]: { flexDirection: 'column' } },
  '.title-container': {
    display: 'flex',
    flexDirection: 'column',
    gap: '32px',
    flex: 1,
    [theme.breakpoints.down('md')]: { gap: '16px', textAlign: 'center' },
  },
  '.title-group': { display: 'flex', flexDirection: 'column', gap: '8px' },
  '.description-container': { display: 'flex', flexDirection: 'column', gap: '16px', flex: 1 },
  '.block-images-container': {
    display: 'flex',
    flexDirection: 'column',
    gap: '40px',
    width: '100%',
    [theme.breakpoints.down('md')]: { gap: '32px' },
  },
  '.images-container': { display: 'flex', gap: '24px', width: '100%', [theme.breakpoints.down('md')]: { flexDirection: 'column' } },
  '.icon-text-container': { display: 'flex', flexDirection: 'column', gap: '8px', alignSelf: 'center' },
  '.icons-container': {
    display: 'flex',
    justifyContent: 'space-between',
    [theme.breakpoints.down('md')]: { flexDirection: 'column', gap: '12px' },
  },
  '.icon-location-container': { display: 'flex', gap: '16px' },
  '.icon-location': {
    display: 'flex',
    padding: '13px',
    alignItems: 'center',
    gap: '10px',
    background: theme.palette.primary[700],
    color: theme.palette.primary[200],
    width: '50px',
    height: '50px',
    borderRadius: '50px',
  },
  '.image-block': {
    width: '576px',
    flexShrink: 0,
    overflow: 'hidden',
    [theme.breakpoints.down('md')]: { width: '100%', height: '300px' },
    '& img': { width: '100%', height: '100%', objectFit: 'cover', borderRadius: '8px' },
    '& iframe': { width: '100%', height: '100%', minHeight: '300px' },
  },
}));

export const AboutSustainabilityStyled = styled('div')(({ theme }) => ({
  background: theme.palette.grey[50],
  padding: '0px 100px 125px 100px',
  color: theme.palette.grey[900],
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center',
  [theme.breakpoints.down('md')]: { padding: '0px' },
  '.title-sustainability': {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '100px 50px 50px 50px',
    textAlign: 'center',
    [theme.breakpoints.down('sm')]: { fontSize: '32px', padding: '100px 0px 50px 0px' },
  },
  '.sustainability-grid-container': {
    display: 'flex',
    justifyContent: 'center',
    [theme.breakpoints.down('md')]: {
      padding: '0px',
      display: 'flex',
      flexDirection: 'column-reverse',
      paddingBottom: '10px',
      alignItems: 'center',
    },
  },
  '.sustainability-grid': {
    display: 'flex',
    flexDirection: 'column',
    gap: '30px',
    width: '40%',
    maxWidth: '540px',
    justifyContent: 'flex-start',
    alignItems: 'center',
    [theme.breakpoints.down('md')]: { width: '90%', padding: '10px', paddingBottom: '50px' },
  },
  '.sustainability-title': { display: 'flex', flexDirection: 'column', wordBreak: 'keep-all' },
  '@media (max-width: 600px)': { '.responsive-break': { display: 'none' } },
}));

export const AboutImpactStyled = styled('div')(({ theme }) => ({
  background: theme.palette.grey[50],
  padding: '0px 0px 80px 0px',
  color: theme.palette.grey[900],
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
  '.title-impact': { display: 'flex', flexDirection: 'column', gap: '16px', padding: '80px 0px', textAlign: 'center' },
  '.impact-grid-container': { display: 'flex', justifyContent: 'center', padding: '100px 0px 0px 0px' },
  '.impact-grid': {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '16px',
    width: 'max-content',
    [theme.breakpoints.down('sm')]: { gridTemplateColumns: 'repeat(2, 1fr)', gap: '8px' },
  },
  '.impact-button': { display: 'flex', flexDirection: 'column', alignItems: 'center' },
}));

export const AboutNumberReportStyled = styled('div')(({ theme }) => ({
  background: theme.palette.grey[50],
  display: 'flex',
  justifyContent: 'center',
  gap: '0px',
  paddingBottom: '48px',
  [theme.breakpoints.down('sm')]: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '50px',
    justifyItems: 'center',
    '& > :first-child': { gridColumn: 'span 2', width: '100%', gap: '10px' },
  },
}));
