'use client';

import { styled } from '@mui/material/styles';

export const RegisterStyled = styled('div')(({ theme }) => ({
  '.register-full-width-section': {
    width: '100%',
    background: theme.palette.grey[50],
    display: 'flex',
    justifyContent: 'center',
    padding: '100px 0px',
    [theme.breakpoints.down('md')]: { padding: '0px' },
  },
  '.register-inner-container': {
    width: '1176px',
    margin: '0 auto',
    display: 'flex',
    justifyContent: 'center',
    [theme.breakpoints.down('lg')]: { width: '100%' },
    [theme.breakpoints.down('md')]: {
      display: 'flex',
      padding: '64px 16px',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '64px',
      width: 'auto',
    },
  },
  '.register-content-container': {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
    [theme.breakpoints.down('md')]: { flexDirection: 'column', justifyContent: 'flex-start', gap: '60px' },
  },
  '.register-text-section': {
    display: 'flex',
    gap: '16px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    width: '576px',
    [theme.breakpoints.down('md')]: { width: '100%' },
  },
  '.register-form': {
    display: 'flex',
    width: '488px',
    height: 'fit-content',
    padding: '32px 28px',
    alignItems: 'flex-start',
    background: theme.palette.grey[25],
    [theme.breakpoints.down('md')]: { width: 'auto', justifyContent: 'center' },
  },
  '#hs-form': { width: '100%', [theme.breakpoints.down('md')]: { width: '100%', justifyContent: 'center' } },
}));

export const RegisterTextSectionStyled = styled('div')(({ theme }) => ({
  display: 'flex',
  flexDirection: 'column',
  '& .text-highlighted-text': { color: theme.palette.primary[800] + ' !important' },
  '.introduction': { display: 'flex', paddingBottom: '24px', flexDirection: 'column', alignItems: 'flex-start', gap: '32px' },
  '.keywords': { display: 'flex', flexDirection: 'column', gap: '8px', alignItems: 'flex-start' },
  '.content': { display: 'flex', flexDirection: 'column', gap: '16px', alignItems: 'flex-start' },
  '.benefits-list': {
    margin: 0,
    paddingLeft: '20px',
    color: theme.palette.primary[800],
    '& li': { marginBottom: '8px', '&:last-child': { marginBottom: 0 } },
  },
  '.divider': { height: '16px', alignSelf: 'stretch', borderBottom: '1px solid ' + theme.palette.grey[200], marginBottom: '16px' },
  '.reasons': { display: 'flex', padding: '24px 0', flexDirection: 'column', alignItems: 'flex-start', gap: '32px' },
  '.reasons-list': {
    margin: 0,
    paddingLeft: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    listStyleType: 'disc',
    '& li': { color: theme.palette.primary[800] },
  },
  '.sponsors-section': { display: 'flex', paddingTop: '24px', flexDirection: 'column', alignItems: 'flex-start', gap: '32px' },
  '.sponsors-main-title': { color: theme.palette.grey[600] },
  '.sponsors-groups-container': { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '32px', width: '376px' },
  '.sponsor-group': { display: 'flex', flexDirection: 'column', gap: '16px' },
  '.sponsor-group-title': { color: theme.palette.grey[600] },
  '.sponsors-logos': {
    display: 'flex',
    paddingBottom: '16px',
    alignItems: 'flex-start',
    alignContent: 'flex-start',
    gap: '16px 24px',
    flexWrap: 'wrap',
    [theme.breakpoints.down('md')]: { width: '376px', justifyContent: 'flex-start' },
  },
  '.logo': { background: '#FFFFFF', width: '176px', height: '60px', display: 'flex', justifyContent: 'center', alignItems: 'center' },
}));

export const SecondaryDarkHeroStyled = styled('div')(({ theme }) => ({
  paddingTop: 'calc(var(--navbar-height, 0px) + 79px)',
  paddingBottom: '50px',
  paddingLeft: '50px',
  paddingRight: '50px',
  display: 'flex',
  flexDirection: 'column',
  gap: '24px',
  backgroundImage: 'url("/Sphere2026.png"), linear-gradient(90deg, #002F5A -7.72%, #20A393 64.95%, #A0FFA7 106.55%)',
  backgroundPosition: 'bottom right, center',
  backgroundRepeat: 'no-repeat, no-repeat',
  backgroundSize: '560px auto, cover',
  [theme.breakpoints.down('sm')]: {
    paddingTop: 'calc(var(--navbar-height, 0px) + 64px)',
    paddingBottom: '50px',
    paddingLeft: '0px',
    paddingRight: '0px',
    alignItems: 'center',
    textAlign: 'center',
    backgroundImage: 'url("/Sphere2026-half.png"), linear-gradient(90deg, #002F5A -7.72%, #20A393 64.95%, #A0FFA7 106.55%)',
    backgroundSize: '50%, cover',
  },
  '.supertitle': { color: theme.palette.primary['100'], letterSpacing: '0.1em' },
  '.header': { display: 'flex', flexDirection: 'column', gap: '0.5em', [theme.breakpoints.down('sm')]: { flexDirection: 'row' } },
  '.title': { color: '#FFFFFF', letterSpacing: '0.1em' },
  '.subtitle': { color: theme.palette.primary['50'], letterSpacing: '0.1em' },
  '.location-container': {
    display: 'flex',
    height: '110px',
    flexDirection: 'column',
    alignSelf: 'flex-end',
    borderRadius: '8px',
    [theme.breakpoints.down('sm')]: { paddingRight: '0px', alignSelf: 'center' },
  },
}));
